rm -f -r configure
rm -f -r ./Makefile.in
rm -f -r ./examples/Makefile.in
rm -f -r config.guess
rm -f -r config.sub
rm -f -r ltmain.sh
rm -f -r config.h.in
rm -f -r autom4te.cache
rm -f -r aclocal.m4
rm -f -r install-sh
rm -f -r SVNREV
rm -f -r build-aux/libtool.m4
rm -f -r build-aux/ltoptions.m4
rm -f -r build-aux/ltsugar.m4
rm -f -r build-aux/ltversion.m4
rm -f -r build-aux/lt~obsolete.m4
rm -f -r libperseus_sdr*
rm -f -r perseusdata
rm -f -r .version
rm -f -r .tarball*

